# Site settings
title: Eamo's Tech Notes
email: eamonncostello |a|t| gmail |d|o|t| com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my Blog. An assortment of various articles covering my experiences
  with Linux, C++14, Mathematics, and anything else I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eamoc.github.io" # the base hostname & protocol for your site
twitter_username: eamoc
github_username:  eamoc

# Build settings
markdown: kramdown
